miscellaneous/tutor/config/routes.rb
Etutor::Application.routes.draw do

  resources :tutors

  root 'tutors#index'

end

miscellaneous/tutor/app/models/tutor.rb
class Tutor < ActiveRecord::Base
	validates :name, :presence => true, :uniqueness => true
	validates :description, :presence => true,
		:length => {:maximum => 2000}
end

miscellaneous/tutor/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

miscellaneous/tutor/app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
  before_action :set_tutor, only: [:show, :edit, :update, :destroy]

  # GET /tutors
  # GET /tutors.json
  def index
    @tutors = Tutor.all
  end

  # GET /tutors/1
  # GET /tutors/1.json
  def show
  end

  # GET /tutors/new
  def new
    @tutor = Tutor.new
  end

  # GET /tutors/1/edit
  def edit
  end

  # POST /tutors
  # POST /tutors.json
  def create
    @tutor = Tutor.new(tutor_params)

    respond_to do |format|
      if @tutor.save
        format.html { redirect_to @tutor, notice: 'Tutor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tutor }
      else
        format.html { render action: 'new' }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutors/1
  # PATCH/PUT /tutors/1.json
  def update
    respond_to do |format|
      if @tutor.update(tutor_params)
        format.html { redirect_to @tutor, notice: 'Tutor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutors/1
  # DELETE /tutors/1.json
  def destroy
    @tutor.destroy
    respond_to do |format|
      format.html { redirect_to tutors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutor
      @tutor = Tutor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tutor_params
      params.require(:tutor).permit(:name, :category, :cost, :description)
    end
end

miscellaneous/tutor/app/helpers/application_helper.rb
module ApplicationHelper
end

miscellaneous/tutor/app/helpers/tutors_helper.rb
module TutorsHelper
end

miscellaneous/tutor/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Tutoring Marketplace</title>
  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag 'application', :media => "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
</head>
<body>
  <div id="main">
    <header>
      <div id="toolbar">
      </div>
      <h1>
        <%= link_to '<span class="c4">T</span><span class="c4">u</span><span class="c4">t</span><span class="c4">o</span><span class="c4">r</span><span class="c4">i</span><span class="c4">n</span><span class="c4">g</span><span> </span><span class="l2">M</span><span class="a3">a</span><span class="r4">r</span><span class="n5">k</span><span class="i6">e</span><span class="g7">t</span><span class="e1">p</span><span class="12">l</span><span class="a3">a</span><span class="r4">c</span><span class="n5">e</span>'.html_safe, root_path %>
      </h1>
      <nav>
        <ul>
          <li><%= link_to "List", tutors_path %></li>
          <li><%= link_to "Create", new_tutor_path %></li>
        </ul>
      </nav>
    </header>
    <% if notice %><p class="notice"><%= notice %></p><% end %>
    <% if alert %><p class="alert"><%= alert %></p><% end %>

    <%= yield %>
	<p class="footer">Note this is a pre-alpha version of the Tutoring Marketplace.</p>
  </div>
</body>
</html>

miscellaneous/tutor/app/views/tutors/_form.html.erb
<%= form_for(@tutor) do |f| %>
  <% if @tutor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tutor.errors.count, "error") %> prohibited this tutor from being saved:</h2>

      <ul>
      <% @tutor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

miscellaneous/tutor/app/views/tutors/edit.html.erb

<h1> Edit <%=  @tutor.name %> </h1>

<br>

<%= form_for @tutor do |f| %>

   <p>
	<%= f.label :name %> : <br>
	<%= f.text_field :name %> <br>
   </p>
   <p>
        <%= f.label :category %> : <br>
        <%= f.text_field :category %> <br>
   </p>
   <p>
        <%= f.label :cost %> : <br>
        <%= f.text_field :cost %> <br>
   </p>
   <p>
	<%= f.label :description %> : <br>
	<%= f.text_area :description, :rows=> 6, :cols=> 60 %> <br>
   </p>
   <p>
        <%= f.submit %> <br>
   </p>

<% end %>


<br>
<%= Time.current  %>

miscellaneous/tutor/app/views/tutors/index.html.erb
<h1> <%= pluralize @tutors.count,"Tutor" %></h1>

<br>

<ul>
	<% @tutors.each do |a| %>
<li> <%= link_to a.name, a %> </li>
		
	<% end %>

</ul>

<br>
<%= link_to "New Tutor", new_tutor_path  %>

<br>
<br>
<%= Time.current  %>

miscellaneous/tutor/app/views/tutors/new.html.erb
<h1> "New Tutor" </h1>
<br>

<%= form_for @tutor do |f| %>

<% if f.object.errors.any? %>
   <div id="error_explanation">
   <h2>The following errors prohibited this form from being saved:</h2>
   <ul>
   <% f.object.errors.full_messages.each do |message| %>
   <li><%= message %></li>
   <% end %>
   </ul>
   </div>
   <% end %>
	
   <p>
	<%= f.label :name %> : <br>
	<%= f.text_field :name %> <br>
   </p>
   <p>
        <%= f.label :category %> : <br>
        <%= f.text_field :category %> <br>
   </p>
   <p>
        <%= f.label :cost %> : <br>
        <%= f.text_field :cost %> <br>
   </p>
   <p>
	<%= f.label :description %> : <br>
	<%= f.text_area :description, :rows=> 6, :cols=> 60 %> <br>
   </p>
   <p>
        <%= f.submit %> <br>
   </p>

<% end %>


<br>
<%= Time.current  %>

miscellaneous/tutor/app/views/tutors/show.html.erb

<h1><%=  @tutor.name %> </h1>

<dl class="info">
	<dt> Category:</dt>
	<dd>
	<%= @tutor.category %>
	</dd>
</dl>

<dl class="info">
        <dt> Cost ($):</dt>
        <dd>
        <%= @tutor.cost %>
        </dd>
</dl>

<div>
	<%= @tutor.description %>
</div>

<br>
<dl class="info">
<dt>Created at:</dt>
<dd>
<%= @tutor.created_at.to_s(:long) + "UTC" %> 
<%= time_ago_in_words @tutor.created_at %>  ago 
</dd>
</dl>

<br>
<%= link_to "Click to Edit",edit_tutor_path(@tutor) %>

<br>
<%= link_to "Click to Delete", @tutor, :data => {:method => :delete,
  :confirm => "are you sure?" } %>

<br>
<%= link_to "Back to All Tutors",tutors_path %>


miscellaneous/tutor/app/views/tutors/update.html.erb

<h1> Update <%=  @tutor.name %> </h1>

<br>

<%= form_for @tutor do |f| %>

   <p>
	<%= f.label :name %> : <br>
	<%= f.text_field :name %> <br>
   </p>
   <p>
        <%= f.label :category %> : <br>
        <%= f.text_field :category %> <br>
   </p>
   <p>
        <%= f.label :cost %> : <br>
        <%= f.text_field :cost %> <br>
   </p>
   <p>
	<%= f.label :description %> : <br>
	<%= f.text_area :description, :rows=> 6, :cols=> 60 %> <br>
   </p>
   <p>
        <%= f.submit %> <br>
   </p>

<% end %>


<br>
<%= Time.current  %>